version: "3.8"

services:
  redis:
    image: redis/redis-stack:latest
    container_name: dispy_redis_stack
    ports:
      - "6379:6379"
      - "8001:8001" # RedisInsight UI
    environment:
      - REDIS_ARGS=--save 60 1000 --appendonly yes
    volumes:
      - ./data/redis:/data
    restart: unless-stopped

volumes:
  redis_data:
    driver: local


