name: dispycluster
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
    # Core web framework (optimisé pour RPi)
    - fastapi==0.100.1
    - uvicorn==0.23.2
    - aiohttp==3.8.5
    - httpx==0.24.1
    - apscheduler==3.9.1
    - requests==2.31.0
    - pydantic==1.10.12
    - dispy==4.15.0
    
    # Monitoring léger
    - prometheus-client==0.17.1
    - psutil==5.9.5
    
    # Web scraping optimisé
    - beautifulsoup4==4.12.2
    - lxml==4.9.3
    - selenium==4.10.0
    
    # Utilitaires essentiels
    - pyyaml==6.0.1
    - click==8.1.7
    - colorama==0.4.6
    - python-dotenv==1.0.0
    
    # SSH et sécurité
    - paramiko==3.2.0
    - cryptography==3.4.8
    
    # Tests légers
    - pytest==7.4.2
    - pytest-asyncio==0.21.1